urls.py
from __future__ import unicode_literals

from django.conf.urls import patterns, url

from .views import Dashboard
from .views import DPSRequestDetail
from .views import DPSRequestCreate
# from .views import DPSRequestUpdate
from .views import DPSRequestDecline

urlpatterns = patterns(
    # pylint: disable=E1120
    '',
    url(r'^dashboard/$', Dashboard.as_view(),
        name="dashboard"),
    url(r'^dpsrequest/(?P<pk>\d+)/$',
        DPSRequestDetail.as_view(),
        name="dpsrequest_detail"),
    url(r'^dpsrequest/add/(?P<event_pk>\d+)/(?P<ct_pk>\d+)/$',
        DPSRequestCreate.as_view(),
        name='dpsrequest_add'),
    # url(r'^dpsrequest/(?P<pk>\d+)/edit$',
    #     DPSRequestUpdate.as_view(),
    #     name='dpsrequest_update'),
    url(r'^dpsrequest/decline/(?P<pk>\d+)/(?P<ct_pk>\d+)/$',
        DPSRequestDecline.as_view(),
        name='dpsrequest_decline'),
    # pylint: enable=E1120
)

models.py
from __future__ import unicode_literals

from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.fields import GenericRelation
from django.contrib.contenttypes.models import ContentType
from django.core.urlresolvers import reverse
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.utils.encoding import python_2_unicode_compatible, smart_text
from django.utils.translation import ugettext_lazy as _

from administration.models import FireService

from emergencies.models import FirstAidAssociation
from emergencies.models import PublicAssistance

from contacts.models import Contact

from ddcs_loire.utils import add_notification_entry


class MedicalRequest(models.Model):
    first_aid_association = models.ForeignKey(
        FirstAidAssociation,
        verbose_name=_('first aid association selected'),
    )
    content_type = models.ForeignKey(ContentType)
    object_id = models.PositiveIntegerField()
    content_object = GenericForeignKey('content_type', 'object_id')

    class Meta:  # pylint: disable=C1001
        abstract = True
        unique_together = ('content_type', 'object_id')
        verbose_name = _('medical request')
        verbose_name_plural = _('medical requests')

    def get_absolute_url(self):
        url = ''.join(['events:',
                       ContentType.objects.get(pk=self.content_type.id).model,
                       '_detail'])
        return reverse(url, kwargs={'pk': self.object_id})


@python_2_unicode_compatible
class MedicalContact(Contact):
    ACTIVITY_CHOICES = (
        ('d', _('doctor')),
        ('n', _('nurse')),
        ('p', _('physiotherapist')),
        ('a', _('private ambulance')),
    )

    activity = models.CharField(_('activity'),
                                max_length=1,
                                choices=ACTIVITY_CHOICES)

    class Meta:  # pylint: disable=C1001
        verbose_name = _('medical contact')
        verbose_name_plural = _('medical contacts')

    def __str__(self):
        return ' '.join([self.get_activity_display().capitalize(), '-',
                         self.first_name.capitalize(),
                         self.last_name.capitalize()])


@python_2_unicode_compatible
class DPSRequest(MedicalRequest):
    GATHERING_ACTIVITY_CHOICES = (
        ('l', _('low')),
        ('r', _('reasonable')),
        ('m', _('medium')),
        ('h', _('high')),
    )
    SITE_ACCESSIBILITY_CHOICES = (
        ('l', _('low')),
        ('r', _('reasonable')),
        ('m', _('medium')),
        ('h', _('high')),
    )
    INTERVENTION_TIME_CHOICES = (
        ('0', _('less than 10 minutes')),
        ('1', _('between 10 and 20 minutes')),
        ('2', _('between 20 and 30 minutes')),
        ('3', _('more than 30 minutes')),
    )

    rescues_day_shift = models.BooleanField(_('rescuers attendance by day'),
                                            default=False)
    rescues_night_shift = models.BooleanField(
        _('rescuers attendance by night'),
        default=False,
    )
    area_length = models.PositiveIntegerField(_('area length'))
    age_scale_from = models.PositiveIntegerField(_('age scale : from'))
    age_scale_to = models.PositiveIntegerField(_('to'))
    people_with_special_needs = models.TextField(
        _('people with special needs'),
    )
    public_attendance_duration = models.PositiveIntegerField(
        _('public attendance duration'),
    )
    # pylint: disable=C0103
    participants_attendance_duration = models.PositiveIntegerField(
        _('participants attendance duration'),
    )
    # pylint: enable=C0103
    public_declared = models.PositiveIntegerField(
        _('predictable public attendance')
    )
    specific_risks = models.TextField(
        _('specific risks'),
        blank=True,
        help_text=_('specific risks help text'),
    )
    gathering_activity = models.CharField(_('gathering activity'),
                                          max_length=1,
                                          choices=GATHERING_ACTIVITY_CHOICES)
    site_accessibility = models.CharField(_('site accessibility'),
                                          max_length=1,
                                          choices=SITE_ACCESSIBILITY_CHOICES)
    intervention_time = models.CharField(_('intervention time'),
                                         max_length=1,
                                         choices=INTERVENTION_TIME_CHOICES)
    ris = models.DecimalField(_('ris'), max_digits=10, decimal_places=2)
    permanent_structure = models.BooleanField(_('permanent structure'),
                                              default=False)
    non_permanent_structure = models.BooleanField(
        _('non permanent structure'),
        default=False,
    )
    public_space = models.BooleanField(_('public space'), default=False)
    stretcher_range = models.PositiveIntegerField(_('stretcher range'))
    ground_slope = models.PositiveIntegerField(_('ground slope'))
    other_access_difficulties = models.TextField(
        _('other access difficulties'),
    )
    fire_service = models.ForeignKey(FireService,
                                     verbose_name=_('fire service'))
    nearest_hospital = models.CharField(_('nearest hospital'), max_length=255)
    public_assistance = models.ForeignKey(PublicAssistance,
                                          verbose_name=_('public assistance'))
    logistic_available = models.CharField(_('logistics available'),
                                          max_length=255)
    meal_provided = models.BooleanField(_('meal provided'), default=False)
    kitchen_available = models.BooleanField(_('kitchen available'),
                                            default=False)
    medical_contact = GenericRelation(
        MedicalContact,
        verbose_name=_('medical contact')
    )

    class Meta(MedicalRequest.Meta):
        verbose_name = _('DPS request')
        verbose_name_plural = _('DPS requests')

    def __str__(self):
        return smart_text(self.content_object.__str__())

    def save(self, *args, **kwargs):  # pylint: disable=E1002
        self.set_ris()
        super(DPSRequest, self).save(*args, **kwargs)

    def set_ris(self):
        # compute public ponderation
        if self.public_declared > 100000:
            public = 100000 + ((self.public_declared - 100000)/2)
        else:
            public = self.public_declared

        # compute intervention time
        intervention_time_ratio = {'0': 0.25, '1': 0.30, '2': 0.35, '3': 0.40}
        intervention_time = intervention_time_ratio[self.intervention_time]

        # compute gathering activity
        gathering_activity_ratio = {'l': 0.25, 'r': 0.30, 'm': 0.35, 'h': 0.40}
        gathering_activity = gathering_activity_ratio[self.gathering_activity]

        # compute intervention time
        site_accessibility_ratio = {'l': 0.25, 'r': 0.30, 'm': 0.35, 'h': 0.40}
        site_accessibility = site_accessibility_ratio[self.site_accessibility]

        # compute risk index
        risk_index = (intervention_time + gathering_activity +
                      site_accessibility)

        # compute ris
        self.ris = round(risk_index * public / 1000, 3)

    def get_rescuers_number(self):
        number = self.ris // 1 + 1
        return number + number % 2

    def notify_creation(self):
        add_notification_entry(
            event=self.content_object,
            agents=self.first_aid_association.rescuer_set.all(),  # noqa pylint: disable=E1101
            subject=_('dps requested'),
            content_object=self.content_object.structure,
        )


@receiver(post_save, sender=DPSRequest)
def log_dps_request_creation(created, instance, **kwargs):
    if created:
        instance.content_object.action_set.create(
            user=instance.content_object.structure.promoter.user,
            action=_('dps request created')
        )
        instance.notify_creation()


@python_2_unicode_compatible
class Intervention(models.Model):
    sort = models.CharField(_('type'), max_length=255,
                            help_text=_('sort help text'))
    number = models.PositiveIntegerField(_('number'))
    dps_request = models.ForeignKey(DPSRequest, verbose_name=_('dps request'))

    class Meta:  # pylint: disable=C1001
        verbose_name = _('intervention')

    def __str__(self):
        return ' '.join(['Intervention -', self.dps_request.__str__()])


@python_2_unicode_compatible
class Evacuation(models.Model):
    sort = models.CharField(_('type'), max_length=255,
                            help_text=_('sort help text'))
    number = models.PositiveIntegerField(_('number'))
    dps_request = models.ForeignKey(DPSRequest, verbose_name=_('dps request'))

    class Meta:  # pylint: disable=C1001
        verbose_name = _('evacuation')

    def __str__(self):
        return ' '.join(['Evacuation -', self.dps_request.__str__()])

templates/medical_requests/dpsrequest_description.html
{% load i18n %}

<div class="panel-heading">
    <h3 class="panel-title"><span class="fa fa-plus-square"></span> {% trans "associated dps request"|capfirst %}
    </h3>
</div>
<ul class="list-group">
    <li class="list-group-item">
        {% trans "first aid association selected"|capfirst %} : {{ dpsrequest.first_aid_association.name }}
    </li>
</ul>
{% if dpsrequest.rescues_day_shift or dpsrequest.rescues_night_shift %}
    <div class="panel-heading">
        <h3 class="panel-title"><span class="fa fa-user-md"></span> {% trans "rescues shifts"|capfirst %}</h3>
    </div>
    <ul class="list-group">
        {% if dpsrequest.rescues_day_shift %}
            <li class="list-group-item">
                {% trans "rescuers attendance by day"|capfirst %}
            </li>
        {% endif %}
        {% if dpsrequest.rescues_night_shift %}
            <li class="list-group-item">
                {% trans "rescuers attendance by night"|capfirst %}
            </li>
        {% endif %}
    </ul>
{% endif %}
<div class="panel-heading">
    <h3 class="panel-title"><span class="fa fa-ambulance"></span> {% trans "nature of the dps request"|capfirst %}</h3>
</div>
<ul class="list-group">
    <li class="list-group-item">
        {% trans "age scale : from"|capfirst %} {{ dpsrequest.age_scale_from }} {% trans "to" %} {{ dpsrequest.age_scale_to }} {% trans "years" %}
    </li>
    <li class="list-group-item">
        {% trans "people with special needs"|capfirst %} : {{ dpsrequest.people_with_special_needs }}
    </li>
    <li class="list-group-item">
        {% trans "specific risks"|capfirst %} : {{ dpsrequest.specific_risks }}
    </li>
    <li class="list-group-item">
        {% trans "public attendance duration"|capfirst %} : {{ dpsrequest.public_attendance_duration }} {% trans 'hours'|capfirst %}
    </li>
    <li class="list-group-item">
        {% trans "participants attendance duration"|capfirst %} : {{ dpsrequest.participants_attendance_duration }} {% trans 'hours'|capfirst %}
    </li>
    <li class="list-group-item">
        {% trans "predictable public attendance"|capfirst %} : {{ dpsrequest.public_declared }} {% trans 'people'|capfirst %}
    </li>
    <li class="list-group-item">
        {% trans "gathering activity"|capfirst %} : {{ dpsrequest.get_gathering_activity_display|capfirst }}
    </li>
    <li class="list-group-item">
        {% trans "site accessibility"|capfirst %} : {{ dpsrequest.get_site_accessibility_display|capfirst }}
    </li>
    <li class="list-group-item">
        {% trans "intervention time"|capfirst %} : {{ dpsrequest.get_intervention_time_display|capfirst }}
    </li>
    <li class="list-group-item">
        {% trans "ris"|capfirst %} : {{ dpsrequest.ris }}
    </li>
    <li class="list-group-item">
        {% trans "number of rescuers"|capfirst %} : {{ dpsrequest.get_rescuers_number }}
    </li>
</ul>
<div class="panel-heading">
    <h3 class="panel-title"><span class="fa fa-ambulance"></span> {% trans "site's accessibility"|capfirst %}</h3>
</div>
<ul class="list-group">
    {% if dpsrequest.permanent_structure %}
        <li class="list-group-item">
            {% trans "permanent structure"|capfirst %}
        </li>
    {% endif %}
    {% if dpsrequest.non_permanent_structure %}
        <li class="list-group-item">
            {% trans "non permanent structure"|capfirst %}
        </li>
    {% endif %}
    {% if dpsrequest.public_space %}
        <li class="list-group-item">
            {% trans "public space"|capfirst %}
        </li>
    {% endif %}
    <li class="list-group-item">
        {% trans "area length"|capfirst %} : {{ dpsrequest.area_length }} km
    </li>
    <li class="list-group-item">
        {% trans "stretcher range"|capfirst %} : {{ dpsrequest.stretcher_range }} m
    </li>
    <li class="list-group-item">
        {% trans "ground slope"|capfirst %} : {{ dpsrequest.ground_slope }} %
    </li>
    <li class="list-group-item">
        {% trans "other access difficulties"|capfirst %} : {{ dpsrequest.other_access_difficulties }}
    </li>
</ul>
<div class="panel-heading">
    <h3 class="panel-title"><span class="fa fa-h-square"></span> {% trans "nearest emergencies services"|capfirst %}</h3>
</div>
<ul class="list-group">
    <li class="list-group-item">
        {% trans "fire service"|capfirst %} : {{ dpsrequest.fire_service }}
    </li>
    <li class="list-group-item">
        {% trans "nearest hospital"|capfirst %} : {{ dpsrequest.nearest_hospital }}
    </li>
</ul>
<div class="panel-heading">
    <h3 class="panel-title"><span class="fa fa-medkit"></span> {% trans "other emergencies on the spot"|capfirst %}</h3>
</div>
<ul class="list-group">
    <li class="list-group-item">
        {% trans "public assistance"|capfirst %} : {{ dpsrequest.public_assistance.name }}
    </li>
</ul>
<div class="panel-heading">
    <h3 class="panel-title"><span class="fa fa-stethoscope"></span> {% trans "logistics"|capfirst %}</h3>
</div>
<ul class="list-group">
    <li class="list-group-item">
        {% trans "logistics available"|capfirst %} : {{ dpsrequest.logistic_available }}
    </li>
    <li class="list-group-item">
        {% trans "meal provided"|capfirst %} : {{ dpsrequest.meal_provided|yesno|title }}
    </li>
    <li class="list-group-item">
        {% trans "kitchen available"|capfirst %} : {{ dpsrequest.kitchen_available|yesno|title }}
    </li>
</ul>
{% include 'medical_requests/medicalcontacts_detail.html' with contacts=dpsrequest.medical_contact %}
{% include 'medical_requests/interventions_detail.html' with interventions=dpsrequest.intervention_set.all only %}
{% include 'medical_requests/evacuations_detail.html' with evacuations=dpsrequest.evacuation_set.all %}

templates/medical_requests/dpsrequest_detail.html
{% extends "events/base.html" %}

{% load url from future %}
{% load i18n %}

{% block head_title %}{% endblock %}
{% block page_title %}
    <h1>{{ object }}</h1>
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-sm-8">
            <ul class="nav nav-pills">
                <li class="active"><a href="#event" data-toggle="pill">{% trans "event"|capfirst %}</a></li>
                <li><a href="#dps" data-toggle="pill">{% trans "associated dps request"|capfirst %}</a></li>
            </ul>
            <div class="tab-content">
                <div id="event" class="panel panel-default tab-pane fade in active">
                    {% include 'events/event_description.html' with  object=dpsrequest.content_object %}
                </div>
                <div id="dps" class="panel panel-default tab-pane fade">
                    {% include 'medical_requests/dpsrequest_description.html' %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/medical_requests/dpsrequest_form.html
{% extends "events/base_form.html" %}

{% load i18n %}
{% load crispy_forms_tags %}

{% block head_title %}{% trans "dps request form"|capfirst %}{% endblock %}
{% block page_title %}
    <h1>{% trans "dps request form"|capfirst %}</h1>
{% endblock %}

{% block form %}
    <form class="form-horizontal" action="" method="post">
        {% crispy form %}
        {% for form in inlines %}
            <fieldset>
                {% if forloop.counter == 1 %}
                    <legend>{% trans 'medical contacts'|capfirst %}</legend>
                {% elif forloop.counter == 2 %}
                    <legend>{% trans 'last edition interventions'|capfirst %}</legend>
                {% else %}
                    <legend>{% trans 'last edition evacuations'|capfirst %}</legend>
                {% endif %}
                {% crispy form form.form.helper %}
            </fieldset>
        {% endfor %}
        <div class="form-actions">
            <input id="submit-id-save" class="btn btn-primary" type="submit" value="{% trans 'submit'|capfirst %}" name="save">
            </input>
        </div>
    </form>
{% endblock %}

templates/medical_requests/dpsrequest_list.html
{% extends "events/base.html" %}

{% load url from future %}
{% load i18n %}

{% block head_title %}{% trans "dashboard"|title %}{% endblock %}
{% block page_title %}
    <h1>{% trans "dashboard"|title %}</h1>
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-sm-6">
            <h3>{% trans 'dps requests'|capfirst %}</h3>
            <div class="panel panel-default">
                <div class="list-group">
                    {% for request in object_list %}
                        <a href="{% url 'medical_requests:dpsrequest_detail' request.id %}" class="list-group-item">{{ request }}</a>
                    {% endfor %}
                </div>
            </div>
        </div>
        <div class="col-sm-6">
            <div class="row">
                {% include "notifications/actions_list.html" %}
            <div class="row">
            </div>
                {% include "notifications/notifications_list.html" %}
            </div>
        </div>
    </div>
{% endblock %}

templates/medical_requests/evacuations_detail.html
{% load i18n %}
{% load humanize %}

{% if evacuations.first %}
    <div class="panel-heading">
        <h3 class="panel-title"><span class="fa fa-ambulance"></span> {% trans "last edition evacuations"|capfirst %}</h3>
    </div>
    <ul class="list-group">
        {% for evacuation in evacuations %}
            <li class="list-group-item">
                {{ evacuation.sort|capfirst }} : {{ evacuation.number|apnumber|capfirst }} 
            </li>
        {% endfor %}
    </ul>
{% endif %}

templates/medical_requests/interventions_detail.html
{% load i18n %}
{% load humanize %}

{% if interventions.first %}
    <div class="panel-heading">
        <h3 class="panel-title"><span class="fa fa-user-md"></span> {% trans "last edition interventions"|capfirst %}</h3>
    </div>
    <ul class="list-group">
        {% for intervention in interventions %}
            <li class="list-group-item">
                {{ intervention.sort|capfirst }} : {{ intervention.number|apnumber|capfirst }} 
            </li>
        {% endfor %}
    </ul>
{% endif %}

templates/medical_requests/medicalcontacts_detail.html
{% load i18n %}

{% if contacts.first %}
    <div class="panel-heading">
        <h3 class="panel-title"><span class="fa fa-phone-square"></span> {% trans "medical contacts"|capfirst %}</h3>
    </div>
    <ul class="list-group">
        {% for contact in contacts.all %}
            <li class="list-group-item">
                {{ contact.get_activity_display|capfirst }} : {{ contact.first_name|capfirst }} {{ contact.last_name|capfirst }} - {{ contact.phone }}
            </li>
        {% endfor %}
    </ul>
{% endif %}